name: CI/CD Pipeline to Debian Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_BACKEND: moreiamoreia/fullstack-backend_v2 
  DOCKER_IMAGE_FRONTEND: moreiamoreia/fullstack-frontend_v2

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Аутентификация в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Сборка и отправка Backend образа
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BACKEND }}:latest

      # 3. Сборка и отправка Frontend образа (nginx)
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_FRONTEND }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # 4. Деплой на удаленный сервер через SSH
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          # Команды, которые выполняются на Debian-сервере:
          script: |
            echo "--- PULLING LATEST DOCKER COMPOSE FILE ---"
            cd /home/${{ secrets.SSH_USERNAME }}
            git pull origin main
            
            echo "--- STARTING DEPLOYMENT ---"
            sudo /usr/local/bin/docker-compose -f docker-compose.yml up --build --force-recreate --remove-orphans -d
            
            echo "Deployment finished successfully."
